// Generated by purs bundle 0.12.0
var PS = {};
(function(exports) {
    "use strict";

  exports.log = function (s) {
    return function () {
      console.log(s);
      return {};
    };
  };
})(PS["Effect.Console"] = PS["Effect.Console"] || {});
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var $foreign = PS["Effect.Console"];
  var Data_Show = PS["Data.Show"];
  var Data_Unit = PS["Data.Unit"];
  var Effect = PS["Effect"];
  exports["log"] = $foreign.log;
})(PS["Effect.Console"] = PS["Effect.Console"] || {});
(function(exports) {
    "use strict";
  var Control_Bind = PS["Control.Bind"];
  var Data_Function = PS["Data.Function"];
  var Data_Semigroup = PS["Data.Semigroup"];
  var Effect = PS["Effect"];
  var Effect_Console = PS["Effect.Console"];
  var Prelude = PS["Prelude"];                 
  var welcome = function (name) {
      return "Hey hey hey " + name;
  };
  var plog = function (msg) {
      return Effect_Console.log("[PS] " + msg);
  };
  var main = function __do() {
      plog("Hello sailor!")();
      return plog(welcome("someone"))();
  };
  exports["plog"] = plog;
  exports["main"] = main;
  exports["welcome"] = welcome;
})(PS["Main"] = PS["Main"] || {});
PS["Main"].main();
